# Generated by Django 4.1.5 on 2023-01-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_main_tag_scope_is_main_article_scopes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='scope',
        ),
    ]
