# Generated by Django 4.1.5 on 2023-01-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_options_rename_tag_scope_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='scope',
            new_name='scopes',
        ),
    ]
