# Generated by Django 4.1.5 on 2023-01-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_scope_scope_scopes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='scopes',
            new_name='tag',
        ),
    ]
